1 3/4 cups all purpose flour, or (plain flour)
3/4 cup unsweetened cocoa powder
1 1/2 teaspoon baking powder
1 1/2 teaspoon baking soda or bi-carb soda
1 teaspoon salt
2 cups white granulated sugar
2 large eggs
1 cup milk
1/2 cup vegetable oil
2 teaspoons pure vanilla extract
1 cup boiling water

CHOCOLATE BUTTERCREAM FROSTING INGREDIENTS
4 oz butter, (120 g | 1/2 cup)
2/3 cup unsweetened cocoa powder
3 cups powdered sugar
1/3 cup milk
1 teaspoon pure vanilla extract 